### ISSUE TITLE
It looks like dynamodb_local_latest.zip location has moved

### ISSUE THREAD

**Issue by tanya-coding** [dmcgillen/lein-dynamodb-local#7]
According to http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html new location is https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip

**Comment by dmcgillen** [comment]
https://github.com/dmcgillen/lein-dynamodb-local/pull/8
