### ISSUE TITLE
0.2.9 points to old download location

### ISSUE THREAD

**Issue by invadersmustdie** [dmcgillen/lein-dynamodb-local#9]
It looks like version 0.2.9 doesn't include https://github.com/dmcgillen/lein-dynamodb-local/commit/e55b47010e8e7138dd20ada653deb2311557ae5a

This leads to broken builds when the zip file isn't cached locally :/

This project is an important building block in our test infrastructure, thanks so far making this possible :)

**Comment by joelittlejohn** [comment]
@dmcgillen Any chance you could cut another release? Cheers

**Comment by dmcgillen** [comment]
Sorry for the delay and thanks @joelittlejohn for the reminder. Should be sorted out now in 0.2.10. Glad this project is useful to you and hope it can be again now it's fixed!
